
ARG VERSION
FROM klakegg/hugo:${VERSION}-ext-ubuntu

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends git sudo nano


# Create a non-root user to use if preferred
ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=hugo

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # [Optional] Add sudo support for the non-root user
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Change default user
USER ${USERNAME}